spring.application.name=smart-waste
spring.datasource.url=jdbc:postgresql://localhost:5433/smartwaste
spring.datasource.username=postgres
spring.datasource.password=00000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8082